config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'tasks#index'
  resources :tasks
  resources :labels
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  namespace :admin do
    resources :users
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 200 }
  validates :deadline, presence: true, length: { maximum: 30 }
  validates :status, presence: true, length: { maximum: 30 }
  validates :priority, presence: true, length: { maximum: 30 }

  scope :search_with_name, -> (search_params) { where(['name LIKE ?', "%#{ search_params }%"]) }
  scope :search_with_status, -> (search_params) { where(['status = ?', "#{ search_params }"]) }
  scope :search_with_name_and_status, -> (name, status) { where(['name LIKE ? and status = ?', "%#{ name }%", "#{ status }"])}
  enum priority:{ 高: 0, 中: 1, 低: 2 }

  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
  if logged_in?
    @tasks = current_user.tasks.order(created_at: :desc).page(params[:page]).per(3)
    if params[:task].present?
      @tasks = @tasks.search_with_name_and_status(params[:task][:name], params[:task][:status]) if params[:task][:name].present? && params[:task][:status].present?
      @tasks = @tasks.search_with_name(params[:task][:name]) if params[:task][:name].present?
      @tasks = @tasks.search_with_status(params[:task][:status]) if params[:task][:status].present?
      if params[:task][:label_id].present?
        label = Label.find(params[:task][:label_id])
        @tasks = label.tasks.where(user_id: current_user.id).page(params[:page]).per(3)
      end
    elsif params[:sort_expired].present?
      @tasks = current_user.tasks.order(deadline: :desc).page(params[:page]).per(3)
    elsif params[:sort_priority].present?
      @tasks = current_user.tasks.order(priority: :asc).page(params[:page]).per(3)
    end
  else
    flash[:notice] = "ログインしてください"
    redirect_to new_session_path
  end
end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.create(task_params)
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
      if @task.update(task_params)
        redirect_to @task, notice: 'Task was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @task.destroy
      redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :detail, :deadline, :status, :priority, label_ids: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name, 'タスク名' %>
  <%= form.text_field :name %>
  <%= form.label :detail, '内容' %>
  <%= form.text_area :detail %>
  <%= form.label :deadline, '終了期限' %>
  <%= form.datetime_select :deadline %>
  <%= form.label :status, '状態' %>
  <%= form.select :status,[[include_blank: true], ["完了","完了"],["着手中","着手中"],["未着手","未着手"]]%>
  <%= form.label :priority, '優先順位' %>
  <%= form.select :priority,Task.priorities.keys, include_blank: true %><br>
  <%= form.label :label, 'ラベル' %>
  <% Label.all.each do |label| %>
    <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
    <%= label.name %> 
  <% end %> 
  <br>
  <%= form.submit '登録する' %>

<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% if admin_user?%>
  <%= link_to 'ユーザー管理画面へ', admin_users_path %>
<% end %>
<%= form_with(model: @tasks, method: :get, url: tasks_path, local: true) do |f| %>
<h1 class="index_task">タスク一覧</h1>

  <div class="task_name">
    <%= f.label(:name, 'タスク名で検索') %>
    <%= f.text_field :name, value: @task %>
  </div>

  <div class="task_status">
    <%= f.label(:status, '状態で検索') %>
    <%= f.select :status, [["完了","完了"],["着手中","着手中"],["未着手","未着手"]], include_blank: true %>
  </div>

    <div class="task_label">
  <%= f.label(:status, 'ラベルで検索') %>
    <%= f.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
  </div>

  <%= f.submit('検索') %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>状態</th>
      <th>優先順位</th>
      <th>ラベル</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr class="task_row">
        <td class="task_name"><%= task.name %></td>
        <td class="task_detail"><%= task.detail %></td>
        <td class="task_deadline"><%= task.deadline %></td>
        <td class="task_status"><%= task.status %></td>
        <td class="task_priority"><%= task.priority %></td>
        <td>
          <% task.labels.each do |label| %>
          <%= label.name %>
          <% end %>
        </td>
        <td><%= link_to '詳細', task, class: 'btn btn-primary' %></td>
        <td><%= link_to '編集', edit_task_path(task), class: 'btn btn-success' %></td>
        <td><%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
    <%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %><br>
    <%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %><br>
    <%= paginate @tasks %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>タスク登録</h1>

<%= render 'form', task: @task %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<h1>タスク詳細</h1>

<p>
  <strong>タスク名:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>内容:</strong>
  <%= @task.detail %>
</p>

<p>
  <strong>終了期限:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>状態:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>優先順位:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>ラベル:</strong>
  <% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %>
</p>

<%= link_to 'Back', tasks_path %>