config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root to: 'tasks#index'
  resources :tasks
  resources :labels
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { maximum: 30 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tasks, dependent: :destroy

  before_destroy :must_not_destroy_last_one_user

  def must_not_destroy_last_one_user
    if User.where(admin: true).count == 1 && self.admin
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  before_action :set_user, only: [:show, :edit, :destroy]

  def index
    @users = User.select(:id, :user_name, :email, :password_digest, :admin).page(params[:page]).per(3)
  end

  def new
    @user = User.new
  end

  def show; end

  private
  def if_not_admin
    redirect_to root_path, notice: '管理者以外はアクセスできません' unless current_user.admin?
  end
  
  # def if_not_admin
  #   unless current_user&.admin?
  #     redirect_to root_path
  #   end
  # end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to tasks_path
    else
      @user = User.new
    end
    
  end

  def create
    if logged_in?
      if admin_user?
        @user = User.new(user_params)
        if @user.save
          redirect_to admin_users_path
        else
          render :new
        end
      else
        render :new
      end
    else
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
      else
        render :new
      end
    end
  end

  def show
    if admin_user?
      @user = User.find(params[:id])
    elsif session[:user_id] == params[:id].to_i
      @user = User.find(params[:id])
    else
      redirect_to tasks_path
    end
  end

  def edit
    if admin_user?
      @user = User.find(params[:id])
    elsif session[:user_id] == params[:id].to_i
      @user = User.find(params[:id])
    else
      redirect_to tasks_path
    end
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user, notice: 'プロフィールは更新されました'
      else
        render :edit
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      redirect_to admin_users_path, notice: 'ユーザーは削除されました'
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>管理画面のユーザー一覧画面</h1>

<div class="signup">
<%= link_to "ユーザーの新規作成", new_admin_user_path %>
</div>

<table class="admin_users">
  <thead>
    <tr>
      <th>ユーザーID</th>
      <th>ユーザー名</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="user_row">
        <td class="user_id"><%= user.id %></td>
        <td class="user_name"><%= user.user_name %></td>
        <td><%= link_to '詳細', user_path(user.id), class: 'btn btn-primary' %>
        <td><%= link_to '削除', user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
    <%= paginate @users %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.user_name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :user_name %>
  <%= f.text_field :user_name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin, 'Admin権限' %>
  <%= f.check_box :admin %>
  <%= f.submit "Create my account" %>
<% end %>